### ISSUE TITLE
希望实装tvoc校准功能，通过更换2105固件额外输出pm10与AQI、主要污染物

### ISSUE THREAD

**Issue by yahuid2002** [louliangsheng/daikin-air-sensor#3]
感谢大佬无私奉献与帮助！经过半个月的学习今天终于成功刷入两台空气盒子，但在使用中发现了一点小问题与，在此提出：
1、原2105固件有pm10数据但是不输出，同时缺少pm1数据，虽然通过编辑2105.h与yaml添加了pm10项目，于esp界面同时正常显示，但在ha里这两项更新存在未知冲突，导致pm2.5与pm10只有随机一个能快速更新，另一个保持约15min/次收录，在翻找资料时发现作者miwyf在旧固件基础上提交了自己修改完善的新2105固件，其中包括了pm1、空气AQI与等级、主要污染物种类判断等功能（https://github.com/miwyf/pm2105）希望可以替换采纳，从而为空气盒子提供更多玩法。
2、tvoc传感器靠化学反应判断，根据产品说明需要每6月或接触大量检测气体后校准一次，否则会故障失灵，原校准功能集成在金制空气app中，刷固件时没有看到该功能代码，目前已看见部分群友tvoc传感器失准降不下去，如果没有相关支持该传感器使用期限堪忧。
3、daikin-bry88ab151k目前已经不再实装精度堪忧的eco2传感器，可以考虑删除描述，tvoc传感器希望调整为与其他检测仪相同的毫克/立方米单位。

**Comment by louliangsheng** [comment]
1.你可以自己尝试编译，我对pm10不感兴趣
2.esphome中sgp30没有主动校准功能，https://esphome.io/components/sensor/sgp30
3.没有意义

**Comment by WalterDSU** [comment]
第一点,我已经在我的库项目添加进去了, 有兴趣可以去看看, 自己编译进去. 
第二点, 估计是根据其他传感来做算法校准的, 具体的算法规则不好搞.
