### ISSUE TITLE
对于TVOC数值的疑问

### ISSUE THREAD

**Issue by SeanChengN** [louliangsheng/daikin-air-sensor#7]
通过查阅资料检测TVOC数值的模块是sgp30，它提供的单位是ppb，esp中输出的单位是µg/m³，在代码中似乎没有转换单位（本人不太懂）
![image](https://github.com/louliangsheng/daikin-air-sensor/assets/20624068/2e9a0b5d-282d-4e1e-99af-7fad19d73394)
我查到转换公式如下（可能不正确）：
第一种：
y（µg/m³）=0.00004009 * x（ppb数值） * 78.9516 （VOC的摩尔质量）* 1000
第二种：
y（µg/m³）=x（ppb数值） * 1.233
第三种：
y（µg/m³）=0.0045 * x（ppb数值） * 1000
https://github.com/home-assistant/architecture/discussions/1004
https://forum.digikey.com/t/sensirion-gas-sensors-faq/5205

**Comment by louliangsheng** [comment]
VOC的摩尔质量不固定，所以系数不同，我给的3.0系数，系数在固件中可调，因为HomeKit中用ug/m3，所以我更喜欢用这个单位。
