### ISSUE TITLE
pm2.5的数据不准确

### ISSUE THREAD

**Issue by yukunyi** [louliangsheng/daikin-air-sensor#9]
一个攀藤pms7003，三个大金的，三个大金的数据都比攀藤的小2至3倍，攀藤的数据和附近的国家监测站的数据是一致的。
攀藤pms7003: 110
三个大金: 30-50

**Comment by louliangsheng** [comment]
和监测站一样并不一定准确，你可以再看看别的pm25传感器数值，pm25检测是局部空气抽样，注定不是太准，趋势一般都是一致的，如果有强迫症，你可以算一下怎么拟合
